CREATE TABLE IF NOT EXISTS fiscal_emitter_config (
  id BIGINT NOT NULL AUTO_INCREMENT,
  provider VARCHAR(40) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  environment VARCHAR(20) NOT NULL,
  company_legal_name VARCHAR(160) NULL,
  company_trade_name VARCHAR(160) NULL,
  cnpj VARCHAR(14) NULL,
  state_registration VARCHAR(32) NULL,
  municipal_registration VARCHAR(32) NULL,
  tax_regime VARCHAR(40) NULL,
  api_base_url VARCHAR(255) NULL,
  webhook_url VARCHAR(255) NULL,
  api_token VARCHAR(255) NULL,
  csc_id VARCHAR(64) NULL,
  csc VARCHAR(255) NULL,
  certificate_base64 LONGTEXT NULL,
  certificate_password VARCHAR(255) NULL,
  nfe_series INT NOT NULL DEFAULT 1,
  nfce_series INT NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_fiscal_emitter_provider (provider),
  KEY idx_fiscal_emitter_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fiscal_document (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pedido_id BIGINT NULL,
  provider VARCHAR(40) NOT NULL,
  model VARCHAR(20) NOT NULL,
  environment VARCHAR(20) NOT NULL,
  status VARCHAR(40) NOT NULL,
  external_reference VARCHAR(120) NOT NULL,
  external_id VARCHAR(120) NULL,
  access_key VARCHAR(64) NULL,
  series INT NULL,
  document_number INT NULL,
  protocol VARCHAR(80) NULL,
  issuer_cnpj VARCHAR(14) NULL,
  recipient_document VARCHAR(20) NULL,
  total_amount DECIMAL(19, 2) NULL,
  issued_at DATETIME(6) NULL,
  authorized_at DATETIME(6) NULL,
  cancelled_at DATETIME(6) NULL,
  last_status_at DATETIME(6) NULL,
  xml_storage_path VARCHAR(512) NULL,
  danfe_storage_path VARCHAR(512) NULL,
  request_payload LONGTEXT NULL,
  response_payload LONGTEXT NULL,
  error_message VARCHAR(500) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_fiscal_document_reference (external_reference),
  KEY idx_fiscal_document_status (status),
  KEY idx_fiscal_document_pedido (pedido_id),
  KEY idx_fiscal_document_provider_model (provider, model),
  CONSTRAINT fk_fiscal_document_pedido
    FOREIGN KEY (pedido_id) REFERENCES pedido (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fiscal_event (
  id BIGINT NOT NULL AUTO_INCREMENT,
  fiscal_document_id BIGINT NOT NULL,
  event_type VARCHAR(40) NOT NULL,
  status_before VARCHAR(40) NULL,
  status_after VARCHAR(40) NULL,
  provider_event_id VARCHAR(120) NULL,
  message VARCHAR(500) NULL,
  payload LONGTEXT NULL,
  processed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_fiscal_event_document (fiscal_document_id),
  KEY idx_fiscal_event_type (event_type),
  CONSTRAINT fk_fiscal_event_document
    FOREIGN KEY (fiscal_document_id) REFERENCES fiscal_document (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
